# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


def pods
  pod 'Reachability'
  pod 'Alamofire'
end

target 'Cryptocurrency Candles' do
  use_frameworks!
  inhibit_all_warnings!
  pods
end
target 'Cryptocurrency CandlesTests' do
  use_frameworks!
  inhibit_all_warnings!
  pods
end
